#!/bin/sh
# Cabal is annoying, so i wrote my own build script


build () {
    cabal install -j --enable-tests
}

test () {
    cabal test &&
    cat dist/test/puffytools-0.0.0-tests.log  
}

clean () {
    cabal clean
}

case $1 in
    build)
        build
        ;;
    test)
        build && test
        ;;
    clean)
        clean &&
        case $2 in
            build)
                build
                ;;
            test)
                build && test
                ;;
            *)
        esac
        ;;
    *)
        clean && build && test
        ;;
esac
